import Foundation
import CoreGraphics

// ─────────────────────────────────────────────────────────────
// L0 幼儿字 · 第三包 30 字（扩展生活常用字）
// 分 5 组：颜色 · 食物 · 家居 · 动作 · 家人
// ─────────────────────────────────────────────────────────────
//
// 坐标归一化 0-1，在米字格中合理居中
// 复杂字做了简化处理，保留骨架，便于 4-5 岁儿童临摹
// 所有笔顺按国家规范《现代汉语通用字笔顺规范》排列
// ─────────────────────────────────────────────────────────────

enum KidsCharactersPack3 {

    // ─── 颜色 6 字 ─────────────────────────────────

    // 红 (简化 6→6 画):  绞丝旁(撇折+撇折+提) + 工(横+竖+横)
    static let 红 = CharacterDef(
        id: "kid:红", glyph: "红", level: 0,
        title: "红", subtitle: "红彤彤的颜色",
        strokes: [
            StrokeSpec(id: "k3_hong_1", name: "撇折",
                       points: [.init(x: 0.22, y: 0.28),
                                .init(x: 0.16, y: 0.42),
                                .init(x: 0.28, y: 0.48)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["绞丝旁第一撇折"], direction: "↙→"),
            StrokeSpec(id: "k3_hong_2", name: "撇折",
                       points: [.init(x: 0.28, y: 0.50),
                                .init(x: 0.18, y: 0.62),
                                .init(x: 0.30, y: 0.68)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["第二撇折"], direction: "↙→"),
            StrokeSpec(id: "k3_hong_3", name: "提",
                       points: [.init(x: 0.18, y: 0.78), .init(x: 0.34, y: 0.70)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["一提收尾"], direction: "↗"),
            StrokeSpec(id: "k3_hong_4", name: "横",
                       points: [.init(x: 0.48, y: 0.38), .init(x: 0.86, y: 0.38)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["工字上横"], direction: "→"),
            StrokeSpec(id: "k3_hong_5", name: "竖",
                       points: [.init(x: 0.66, y: 0.38), .init(x: 0.66, y: 0.66)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["工字一竖"], direction: "↓"),
            StrokeSpec(id: "k3_hong_6", name: "横",
                       points: [.init(x: 0.46, y: 0.66), .init(x: 0.88, y: 0.66)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["工字底横"], direction: "→")
        ]
    )

    // 黄 (简化 11→7 画):  艹头 + 日/由 + 八
    static let 黄 = CharacterDef(
        id: "kid:黄", glyph: "黄", level: 0,
        title: "黄", subtitle: "黄澄澄的颜色",
        strokes: [
            StrokeSpec(id: "k3_huang_1", name: "横",
                       points: [.init(x: 0.18, y: 0.22), .init(x: 0.82, y: 0.22)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["上面长横"], direction: "→"),
            StrokeSpec(id: "k3_huang_2", name: "竖",
                       points: [.init(x: 0.32, y: 0.14), .init(x: 0.32, y: 0.36)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["艹左竖"], direction: "↓"),
            StrokeSpec(id: "k3_huang_3", name: "竖",
                       points: [.init(x: 0.68, y: 0.14), .init(x: 0.68, y: 0.36)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["艹右竖"], direction: "↓"),
            StrokeSpec(id: "k3_huang_4", name: "横折",
                       points: [.init(x: 0.30, y: 0.42),
                                .init(x: 0.70, y: 0.42),
                                .init(x: 0.70, y: 0.66)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["中间横折"], direction: "→↓"),
            StrokeSpec(id: "k3_huang_5", name: "横",
                       points: [.init(x: 0.30, y: 0.66), .init(x: 0.70, y: 0.66)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["中间横"], direction: "→"),
            StrokeSpec(id: "k3_huang_6", name: "撇",
                       points: [.init(x: 0.40, y: 0.72),
                                .init(x: 0.28, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["左撇"], direction: "↙"),
            StrokeSpec(id: "k3_huang_7", name: "点",
                       points: [.init(x: 0.60, y: 0.72), .init(x: 0.74, y: 0.86)],
                       widthStart: 0.03, widthEnd: 0.09,
                       tips: ["右点"], direction: "●")
        ]
    )

    // 蓝 (简化 12→7 画): 艹 + 监的骨架
    static let 蓝 = CharacterDef(
        id: "kid:蓝", glyph: "蓝", level: 0,
        title: "蓝", subtitle: "像大海的颜色",
        strokes: [
            StrokeSpec(id: "k3_lan_1", name: "横",
                       points: [.init(x: 0.18, y: 0.22), .init(x: 0.82, y: 0.22)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["草字头一横"], direction: "→"),
            StrokeSpec(id: "k3_lan_2", name: "竖",
                       points: [.init(x: 0.34, y: 0.14), .init(x: 0.34, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["草字头左竖"], direction: "↓"),
            StrokeSpec(id: "k3_lan_3", name: "竖",
                       points: [.init(x: 0.66, y: 0.14), .init(x: 0.66, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["草字头右竖"], direction: "↓"),
            StrokeSpec(id: "k3_lan_4", name: "竖",
                       points: [.init(x: 0.22, y: 0.40), .init(x: 0.22, y: 0.70)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["左边一竖"], direction: "↓"),
            StrokeSpec(id: "k3_lan_5", name: "横折",
                       points: [.init(x: 0.36, y: 0.40),
                                .init(x: 0.78, y: 0.40),
                                .init(x: 0.78, y: 0.68)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["上部横折"], direction: "→↓"),
            StrokeSpec(id: "k3_lan_6", name: "横",
                       points: [.init(x: 0.24, y: 0.56), .init(x: 0.76, y: 0.56)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["中间一横"], direction: "→"),
            StrokeSpec(id: "k3_lan_7", name: "横",
                       points: [.init(x: 0.16, y: 0.82), .init(x: 0.84, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["最底一横（皿底）"], direction: "→")
        ]
    )

    // 绿 (简化 11→7 画): 绞丝旁 + 录简化
    static let 绿 = CharacterDef(
        id: "kid:绿", glyph: "绿", level: 0,
        title: "绿", subtitle: "像小草的颜色",
        strokes: [
            StrokeSpec(id: "k3_lv_1", name: "撇折",
                       points: [.init(x: 0.22, y: 0.28),
                                .init(x: 0.16, y: 0.42),
                                .init(x: 0.28, y: 0.48)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["绞丝旁第一撇折"], direction: "↙→"),
            StrokeSpec(id: "k3_lv_2", name: "撇折",
                       points: [.init(x: 0.28, y: 0.50),
                                .init(x: 0.18, y: 0.62),
                                .init(x: 0.30, y: 0.68)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["第二撇折"], direction: "↙→"),
            StrokeSpec(id: "k3_lv_3", name: "提",
                       points: [.init(x: 0.18, y: 0.78), .init(x: 0.34, y: 0.70)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["一提收尾"], direction: "↗"),
            StrokeSpec(id: "k3_lv_4", name: "横折",
                       points: [.init(x: 0.46, y: 0.24),
                                .init(x: 0.84, y: 0.24),
                                .init(x: 0.84, y: 0.44)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["右上小框"], direction: "→↓"),
            StrokeSpec(id: "k3_lv_5", name: "横",
                       points: [.init(x: 0.46, y: 0.44), .init(x: 0.84, y: 0.44)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["小框封底"], direction: "→"),
            StrokeSpec(id: "k3_lv_6", name: "竖",
                       points: [.init(x: 0.64, y: 0.50), .init(x: 0.64, y: 0.72)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中间长竖"], direction: "↓"),
            StrokeSpec(id: "k3_lv_7", name: "捺",
                       points: [.init(x: 0.54, y: 0.58),
                                .init(x: 0.70, y: 0.72),
                                .init(x: 0.88, y: 0.84)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["右下一捺"], direction: "↘")
        ]
    )

    // 白 (5 画): 撇 + 竖 + 横折 + 横 + 横
    static let 白 = CharacterDef(
        id: "kid:白", glyph: "白", level: 0,
        title: "白", subtitle: "白云白雪都白白",
        strokes: [
            StrokeSpec(id: "k3_bai_1", name: "撇",
                       points: [.init(x: 0.50, y: 0.16),
                                .init(x: 0.38, y: 0.22),
                                .init(x: 0.30, y: 0.30)],
                       widthStart: 0.08, widthEnd: 0.03,
                       tips: ["上面一小撇"], direction: "↙"),
            StrokeSpec(id: "k3_bai_2", name: "竖",
                       points: [.init(x: 0.28, y: 0.30), .init(x: 0.28, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["左边一竖"], direction: "↓"),
            StrokeSpec(id: "k3_bai_3", name: "横折",
                       points: [.init(x: 0.28, y: 0.30),
                                .init(x: 0.74, y: 0.30),
                                .init(x: 0.74, y: 0.82)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["右边横折"], direction: "→↓"),
            StrokeSpec(id: "k3_bai_4", name: "横",
                       points: [.init(x: 0.28, y: 0.52), .init(x: 0.74, y: 0.52)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["中间一横"], direction: "→"),
            StrokeSpec(id: "k3_bai_5", name: "横",
                       points: [.init(x: 0.28, y: 0.82), .init(x: 0.74, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.07,
                       tips: ["底横封口"], direction: "→")
        ]
    )

    // 黑 (简化 12→7 画)
    static let 黑 = CharacterDef(
        id: "kid:黑", glyph: "黑", level: 0,
        title: "黑", subtitle: "黑漆漆的颜色",
        strokes: [
            StrokeSpec(id: "k3_hei_1", name: "竖",
                       points: [.init(x: 0.30, y: 0.18), .init(x: 0.30, y: 0.50)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["上面左竖"], direction: "↓"),
            StrokeSpec(id: "k3_hei_2", name: "横折",
                       points: [.init(x: 0.30, y: 0.18),
                                .init(x: 0.70, y: 0.18),
                                .init(x: 0.70, y: 0.50)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["上面横折"], direction: "→↓"),
            StrokeSpec(id: "k3_hei_3", name: "横",
                       points: [.init(x: 0.30, y: 0.34), .init(x: 0.70, y: 0.34)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["中间一横"], direction: "→"),
            StrokeSpec(id: "k3_hei_4", name: "横",
                       points: [.init(x: 0.30, y: 0.50), .init(x: 0.70, y: 0.50)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["里字底横"], direction: "→"),
            StrokeSpec(id: "k3_hei_5", name: "长横",
                       points: [.init(x: 0.14, y: 0.60), .init(x: 0.86, y: 0.60)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["长横一划"], direction: "→"),
            StrokeSpec(id: "k3_hei_6", name: "点",
                       points: [.init(x: 0.26, y: 0.72), .init(x: 0.24, y: 0.82)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["四点底第一点"], direction: "●"),
            StrokeSpec(id: "k3_hei_7", name: "点",
                       points: [.init(x: 0.44, y: 0.72), .init(x: 0.44, y: 0.82)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["第二点"], direction: "●"),
            StrokeSpec(id: "k3_hei_8", name: "点",
                       points: [.init(x: 0.76, y: 0.72), .init(x: 0.78, y: 0.82)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["最后一点"], direction: "●")
        ]
    )

    // ─── 食物 6 字 ─────────────────────────────────

    // 米 (6 画): 点 + 撇 + 横 + 竖 + 撇 + 捺
    static let 米 = CharacterDef(
        id: "kid:米", glyph: "米", level: 0,
        title: "米", subtitle: "白白的大米饭",
        strokes: [
            StrokeSpec(id: "k3_mi_1", name: "点",
                       points: [.init(x: 0.30, y: 0.22), .init(x: 0.38, y: 0.34)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["左上一点"], direction: "●"),
            StrokeSpec(id: "k3_mi_2", name: "撇",
                       points: [.init(x: 0.70, y: 0.22),
                                .init(x: 0.62, y: 0.34)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["右上一撇"], direction: "↙"),
            StrokeSpec(id: "k3_mi_3", name: "横",
                       points: [.init(x: 0.16, y: 0.46), .init(x: 0.84, y: 0.46)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["中间长横"], direction: "→"),
            StrokeSpec(id: "k3_mi_4", name: "竖",
                       points: [.init(x: 0.50, y: 0.20), .init(x: 0.50, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中间一竖"], direction: "↓"),
            StrokeSpec(id: "k3_mi_5", name: "撇",
                       points: [.init(x: 0.44, y: 0.54),
                                .init(x: 0.22, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["左下撇"], direction: "↙"),
            StrokeSpec(id: "k3_mi_6", name: "捺",
                       points: [.init(x: 0.56, y: 0.54),
                                .init(x: 0.78, y: 0.82)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["右下捺"], direction: "↘")
        ]
    )

    // 奶 (5 画): 女字旁(撇点+撇+横) + 乃(横折折折钩+撇)
    static let 奶 = CharacterDef(
        id: "kid:奶", glyph: "奶", level: 0,
        title: "奶", subtitle: "香香的牛奶",
        strokes: [
            StrokeSpec(id: "k3_nai_1", name: "撇点",
                       points: [.init(x: 0.32, y: 0.24),
                                .init(x: 0.16, y: 0.46),
                                .init(x: 0.30, y: 0.58)],
                       widthStart: 0.07, widthEnd: 0.05,
                       tips: ["女字旁撇点"], direction: "↙↘"),
            StrokeSpec(id: "k3_nai_2", name: "撇",
                       points: [.init(x: 0.38, y: 0.34),
                                .init(x: 0.22, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["女字旁长撇"], direction: "↙"),
            StrokeSpec(id: "k3_nai_3", name: "提",
                       points: [.init(x: 0.16, y: 0.72), .init(x: 0.40, y: 0.66)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["女字旁一提"], direction: "↗"),
            StrokeSpec(id: "k3_nai_4", name: "横折折折钩",
                       points: [.init(x: 0.50, y: 0.30),
                                .init(x: 0.82, y: 0.30),
                                .init(x: 0.82, y: 0.62),
                                .init(x: 0.68, y: 0.56)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["乃字横折折折钩"], direction: "→↓↖"),
            StrokeSpec(id: "k3_nai_5", name: "撇",
                       points: [.init(x: 0.70, y: 0.44),
                                .init(x: 0.50, y: 0.84)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["最后一撇"], direction: "↙")
        ]
    )

    // 饭 (7 画): 饣(撇+横钩+竖提) + 反(横+撇+横+捺)简化
    static let 饭 = CharacterDef(
        id: "kid:饭", glyph: "饭", level: 0,
        title: "饭", subtitle: "香喷喷的米饭",
        strokes: [
            StrokeSpec(id: "k3_fan_1", name: "撇",
                       points: [.init(x: 0.32, y: 0.18),
                                .init(x: 0.20, y: 0.36)],
                       widthStart: 0.08, widthEnd: 0.03,
                       tips: ["食字旁一撇"], direction: "↙"),
            StrokeSpec(id: "k3_fan_2", name: "横钩",
                       points: [.init(x: 0.14, y: 0.36),
                                .init(x: 0.40, y: 0.36),
                                .init(x: 0.34, y: 0.44)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["食字旁横钩"], direction: "→↙"),
            StrokeSpec(id: "k3_fan_3", name: "竖提",
                       points: [.init(x: 0.26, y: 0.48),
                                .init(x: 0.26, y: 0.78),
                                .init(x: 0.40, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.02,
                       tips: ["食字旁竖提"], direction: "↓↗"),
            StrokeSpec(id: "k3_fan_4", name: "横",
                       points: [.init(x: 0.48, y: 0.28), .init(x: 0.84, y: 0.28)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["反字一横"], direction: "→"),
            StrokeSpec(id: "k3_fan_5", name: "撇",
                       points: [.init(x: 0.58, y: 0.22),
                                .init(x: 0.48, y: 0.50),
                                .init(x: 0.44, y: 0.82)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["反字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_fan_6", name: "横",
                       points: [.init(x: 0.50, y: 0.58), .init(x: 0.78, y: 0.58)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["又字横"], direction: "→"),
            StrokeSpec(id: "k3_fan_7", name: "捺",
                       points: [.init(x: 0.62, y: 0.58),
                                .init(x: 0.72, y: 0.70),
                                .init(x: 0.88, y: 0.84)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["又字一捺"], direction: "↘")
        ]
    )

    // 菜 (简化 11→7 画): 艹 + 采骨架
    static let 菜 = CharacterDef(
        id: "kid:菜", glyph: "菜", level: 0,
        title: "菜", subtitle: "新鲜的蔬菜",
        strokes: [
            StrokeSpec(id: "k3_cai_1", name: "横",
                       points: [.init(x: 0.16, y: 0.20), .init(x: 0.84, y: 0.20)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["草字头横"], direction: "→"),
            StrokeSpec(id: "k3_cai_2", name: "竖",
                       points: [.init(x: 0.34, y: 0.14), .init(x: 0.34, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["草字头左竖"], direction: "↓"),
            StrokeSpec(id: "k3_cai_3", name: "竖",
                       points: [.init(x: 0.66, y: 0.14), .init(x: 0.66, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["草字头右竖"], direction: "↓"),
            StrokeSpec(id: "k3_cai_4", name: "撇",
                       points: [.init(x: 0.50, y: 0.38),
                                .init(x: 0.36, y: 0.50)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["爪字小撇"], direction: "↙"),
            StrokeSpec(id: "k3_cai_5", name: "横",
                       points: [.init(x: 0.24, y: 0.54), .init(x: 0.78, y: 0.54)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["中间一横"], direction: "→"),
            StrokeSpec(id: "k3_cai_6", name: "竖",
                       points: [.init(x: 0.50, y: 0.54), .init(x: 0.50, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中竖"], direction: "↓"),
            StrokeSpec(id: "k3_cai_7", name: "撇",
                       points: [.init(x: 0.44, y: 0.62),
                                .init(x: 0.22, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["左撇"], direction: "↙"),
            StrokeSpec(id: "k3_cai_8", name: "捺",
                       points: [.init(x: 0.56, y: 0.62),
                                .init(x: 0.80, y: 0.84)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["右捺"], direction: "↘")
        ]
    )

    // 果 (8 画): 日 + 木
    static let 果 = CharacterDef(
        id: "kid:果", glyph: "果", level: 0,
        title: "果", subtitle: "甜甜的水果",
        strokes: [
            StrokeSpec(id: "k3_guo_1", name: "竖",
                       points: [.init(x: 0.30, y: 0.18), .init(x: 0.30, y: 0.52)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["日字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_guo_2", name: "横折",
                       points: [.init(x: 0.30, y: 0.18),
                                .init(x: 0.70, y: 0.18),
                                .init(x: 0.70, y: 0.52)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["日字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_guo_3", name: "横",
                       points: [.init(x: 0.30, y: 0.36), .init(x: 0.70, y: 0.36)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["日字中横"], direction: "→"),
            StrokeSpec(id: "k3_guo_4", name: "横",
                       points: [.init(x: 0.30, y: 0.52), .init(x: 0.70, y: 0.52)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["日字底横"], direction: "→"),
            StrokeSpec(id: "k3_guo_5", name: "横",
                       points: [.init(x: 0.14, y: 0.60), .init(x: 0.86, y: 0.60)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["木字长横"], direction: "→"),
            StrokeSpec(id: "k3_guo_6", name: "竖",
                       points: [.init(x: 0.50, y: 0.52), .init(x: 0.50, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["木字竖"], direction: "↓"),
            StrokeSpec(id: "k3_guo_7", name: "撇",
                       points: [.init(x: 0.44, y: 0.66),
                                .init(x: 0.22, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["木字撇"], direction: "↙"),
            StrokeSpec(id: "k3_guo_8", name: "捺",
                       points: [.init(x: 0.56, y: 0.66),
                                .init(x: 0.78, y: 0.86)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["木字捺"], direction: "↘")
        ]
    )

    // 吃 (6 画): 口 + 乞
    static let 吃 = CharacterDef(
        id: "kid:吃", glyph: "吃", level: 0,
        title: "吃", subtitle: "张嘴吃东西",
        strokes: [
            StrokeSpec(id: "k3_chi_1", name: "竖",
                       points: [.init(x: 0.16, y: 0.42), .init(x: 0.16, y: 0.72)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["口字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_chi_2", name: "横折",
                       points: [.init(x: 0.16, y: 0.42),
                                .init(x: 0.40, y: 0.42),
                                .init(x: 0.40, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_chi_3", name: "横",
                       points: [.init(x: 0.16, y: 0.72), .init(x: 0.40, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字底横"], direction: "→"),
            StrokeSpec(id: "k3_chi_4", name: "撇",
                       points: [.init(x: 0.72, y: 0.22),
                                .init(x: 0.54, y: 0.40)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["乞字撇"], direction: "↙"),
            StrokeSpec(id: "k3_chi_5", name: "横",
                       points: [.init(x: 0.52, y: 0.44), .init(x: 0.88, y: 0.44)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["乞字横"], direction: "→"),
            StrokeSpec(id: "k3_chi_6", name: "横折弯钩",
                       points: [.init(x: 0.54, y: 0.58),
                                .init(x: 0.86, y: 0.58),
                                .init(x: 0.86, y: 0.80),
                                .init(x: 0.74, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["乞字横折弯钩"], direction: "→↓↖")
        ]
    )

    // ─── 家居 6 字 ─────────────────────────────────

    // 家 (简化 10→7 画): 宀头 + 豕骨架
    static let 家 = CharacterDef(
        id: "kid:家", glyph: "家", level: 0,
        title: "家", subtitle: "温暖的家",
        strokes: [
            StrokeSpec(id: "k3_jia_1", name: "点",
                       points: [.init(x: 0.48, y: 0.12), .init(x: 0.52, y: 0.22)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["宝盖头一点"], direction: "●"),
            StrokeSpec(id: "k3_jia_2", name: "点",
                       points: [.init(x: 0.20, y: 0.26), .init(x: 0.18, y: 0.36)],
                       widthStart: 0.03, widthEnd: 0.07,
                       tips: ["宝盖头左点"], direction: "●"),
            StrokeSpec(id: "k3_jia_3", name: "横钩",
                       points: [.init(x: 0.16, y: 0.30),
                                .init(x: 0.84, y: 0.30),
                                .init(x: 0.78, y: 0.38)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["宝盖头横钩"], direction: "→↙"),
            StrokeSpec(id: "k3_jia_4", name: "横",
                       points: [.init(x: 0.30, y: 0.48), .init(x: 0.70, y: 0.48)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["豕字一横"], direction: "→"),
            StrokeSpec(id: "k3_jia_5", name: "撇",
                       points: [.init(x: 0.48, y: 0.40),
                                .init(x: 0.30, y: 0.68),
                                .init(x: 0.18, y: 0.86)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["长撇"], direction: "↙"),
            StrokeSpec(id: "k3_jia_6", name: "撇",
                       points: [.init(x: 0.56, y: 0.56),
                                .init(x: 0.42, y: 0.78)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["中撇"], direction: "↙"),
            StrokeSpec(id: "k3_jia_7", name: "捺",
                       points: [.init(x: 0.50, y: 0.50),
                                .init(x: 0.68, y: 0.70),
                                .init(x: 0.86, y: 0.86)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["右下长捺"], direction: "↘")
        ]
    )

    // 门 (3 画): 点 + 竖 + 横折钩
    static let 门 = CharacterDef(
        id: "kid:门", glyph: "门", level: 0,
        title: "门", subtitle: "推开一扇门",
        strokes: [
            StrokeSpec(id: "k3_men_1", name: "点",
                       points: [.init(x: 0.22, y: 0.18), .init(x: 0.26, y: 0.30)],
                       widthStart: 0.03, widthEnd: 0.09,
                       tips: ["左上一点"], direction: "●"),
            StrokeSpec(id: "k3_men_2", name: "竖",
                       points: [.init(x: 0.22, y: 0.36), .init(x: 0.22, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["左边一长竖"], direction: "↓"),
            StrokeSpec(id: "k3_men_3", name: "横折钩",
                       points: [.init(x: 0.34, y: 0.30),
                                .init(x: 0.80, y: 0.30),
                                .init(x: 0.80, y: 0.82),
                                .init(x: 0.70, y: 0.76)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["右边横折钩"], direction: "→↓↖")
        ]
    )

    // 窗 (简化 12→8 画): 穴 + 囱骨架
    static let 窗 = CharacterDef(
        id: "kid:窗", glyph: "窗", level: 0,
        title: "窗", subtitle: "打开小窗户",
        strokes: [
            StrokeSpec(id: "k3_chuang_1", name: "点",
                       points: [.init(x: 0.48, y: 0.10), .init(x: 0.52, y: 0.20)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["宝盖头顶点"], direction: "●"),
            StrokeSpec(id: "k3_chuang_2", name: "点",
                       points: [.init(x: 0.20, y: 0.24), .init(x: 0.18, y: 0.34)],
                       widthStart: 0.03, widthEnd: 0.07,
                       tips: ["宝盖头左点"], direction: "●"),
            StrokeSpec(id: "k3_chuang_3", name: "横钩",
                       points: [.init(x: 0.16, y: 0.28),
                                .init(x: 0.84, y: 0.28),
                                .init(x: 0.78, y: 0.36)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["宝盖横钩"], direction: "→↙"),
            StrokeSpec(id: "k3_chuang_4", name: "撇",
                       points: [.init(x: 0.38, y: 0.38),
                                .init(x: 0.28, y: 0.52)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["穴下小撇"], direction: "↙"),
            StrokeSpec(id: "k3_chuang_5", name: "点",
                       points: [.init(x: 0.60, y: 0.40), .init(x: 0.68, y: 0.50)],
                       widthStart: 0.03, widthEnd: 0.07,
                       tips: ["穴下一点"], direction: "●"),
            StrokeSpec(id: "k3_chuang_6", name: "竖",
                       points: [.init(x: 0.22, y: 0.56), .init(x: 0.22, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["囱字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_chuang_7", name: "横折",
                       points: [.init(x: 0.22, y: 0.56),
                                .init(x: 0.78, y: 0.56),
                                .init(x: 0.78, y: 0.84)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["囱字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_chuang_8", name: "横",
                       points: [.init(x: 0.22, y: 0.84), .init(x: 0.78, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.07,
                       tips: ["囱字底横"], direction: "→")
        ]
    )

    // 床 (7 画): 广 + 木
    static let 床 = CharacterDef(
        id: "kid:床", glyph: "床", level: 0,
        title: "床", subtitle: "睡觉的小床",
        strokes: [
            StrokeSpec(id: "k3_chuangB_1", name: "点",
                       points: [.init(x: 0.44, y: 0.14), .init(x: 0.48, y: 0.24)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["广字头一点"], direction: "●"),
            StrokeSpec(id: "k3_chuangB_2", name: "横",
                       points: [.init(x: 0.18, y: 0.28), .init(x: 0.82, y: 0.28)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["广字头一横"], direction: "→"),
            StrokeSpec(id: "k3_chuangB_3", name: "撇",
                       points: [.init(x: 0.22, y: 0.28),
                                .init(x: 0.16, y: 0.56),
                                .init(x: 0.14, y: 0.84)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["广字头长撇"], direction: "↙"),
            StrokeSpec(id: "k3_chuangB_4", name: "横",
                       points: [.init(x: 0.30, y: 0.52), .init(x: 0.86, y: 0.52)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["木字横"], direction: "→"),
            StrokeSpec(id: "k3_chuangB_5", name: "竖",
                       points: [.init(x: 0.58, y: 0.40), .init(x: 0.58, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["木字竖"], direction: "↓"),
            StrokeSpec(id: "k3_chuangB_6", name: "撇",
                       points: [.init(x: 0.52, y: 0.60),
                                .init(x: 0.34, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["木字撇"], direction: "↙"),
            StrokeSpec(id: "k3_chuangB_7", name: "捺",
                       points: [.init(x: 0.64, y: 0.60),
                                .init(x: 0.84, y: 0.84)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["木字捺"], direction: "↘")
        ]
    )

    // 桌 (简化 10→7 画): 上部骨架 + 木
    static let 桌 = CharacterDef(
        id: "kid:桌", glyph: "桌", level: 0,
        title: "桌", subtitle: "小桌子吃饭",
        strokes: [
            StrokeSpec(id: "k3_zhuo_1", name: "竖",
                       points: [.init(x: 0.50, y: 0.10), .init(x: 0.50, y: 0.20)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["上面小短竖"], direction: "↓"),
            StrokeSpec(id: "k3_zhuo_2", name: "竖",
                       points: [.init(x: 0.34, y: 0.22), .init(x: 0.34, y: 0.42)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["日字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_zhuo_3", name: "横折",
                       points: [.init(x: 0.34, y: 0.22),
                                .init(x: 0.66, y: 0.22),
                                .init(x: 0.66, y: 0.42)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["日字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_zhuo_4", name: "横",
                       points: [.init(x: 0.34, y: 0.42), .init(x: 0.66, y: 0.42)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["日字底横"], direction: "→"),
            StrokeSpec(id: "k3_zhuo_5", name: "横",
                       points: [.init(x: 0.14, y: 0.54), .init(x: 0.86, y: 0.54)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["木字长横"], direction: "→"),
            StrokeSpec(id: "k3_zhuo_6", name: "竖",
                       points: [.init(x: 0.50, y: 0.42), .init(x: 0.50, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["木字一竖"], direction: "↓"),
            StrokeSpec(id: "k3_zhuo_7", name: "撇",
                       points: [.init(x: 0.44, y: 0.62),
                                .init(x: 0.20, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["木字撇"], direction: "↙"),
            StrokeSpec(id: "k3_zhuo_8", name: "捺",
                       points: [.init(x: 0.56, y: 0.62),
                                .init(x: 0.80, y: 0.86)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["木字捺"], direction: "↘")
        ]
    )

    // 椅 (简化 12→7 画): 木 + 奇骨架
    static let 椅 = CharacterDef(
        id: "kid:椅", glyph: "椅", level: 0,
        title: "椅", subtitle: "坐在椅子上",
        strokes: [
            StrokeSpec(id: "k3_yi_1", name: "横",
                       points: [.init(x: 0.10, y: 0.36), .init(x: 0.36, y: 0.36)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["木字旁横"], direction: "→"),
            StrokeSpec(id: "k3_yi_2", name: "竖",
                       points: [.init(x: 0.22, y: 0.22), .init(x: 0.22, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["木字旁竖"], direction: "↓"),
            StrokeSpec(id: "k3_yi_3", name: "撇",
                       points: [.init(x: 0.20, y: 0.50),
                                .init(x: 0.08, y: 0.64)],
                       widthStart: 0.06, widthEnd: 0.02,
                       tips: ["木字旁撇"], direction: "↙"),
            StrokeSpec(id: "k3_yi_4", name: "点",
                       points: [.init(x: 0.28, y: 0.58), .init(x: 0.36, y: 0.66)],
                       widthStart: 0.03, widthEnd: 0.07,
                       tips: ["木字旁点"], direction: "●"),
            StrokeSpec(id: "k3_yi_5", name: "横",
                       points: [.init(x: 0.46, y: 0.24), .init(x: 0.84, y: 0.24)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["大字头横"], direction: "→"),
            StrokeSpec(id: "k3_yi_6", name: "撇",
                       points: [.init(x: 0.64, y: 0.18),
                                .init(x: 0.44, y: 0.52)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["大字头撇"], direction: "↙"),
            StrokeSpec(id: "k3_yi_7", name: "捺",
                       points: [.init(x: 0.64, y: 0.18),
                                .init(x: 0.86, y: 0.52)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["大字头捺"], direction: "↘"),
            StrokeSpec(id: "k3_yi_8", name: "竖",
                       points: [.init(x: 0.52, y: 0.58), .init(x: 0.52, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["可字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_yi_9", name: "横折",
                       points: [.init(x: 0.52, y: 0.58),
                                .init(x: 0.82, y: 0.58),
                                .init(x: 0.82, y: 0.82)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["可字横折"], direction: "→↓")
        ]
    )

    // ─── 动作 6 字 ─────────────────────────────────

    // 看 (简化 9→7 画): 手 + 目
    static let 看 = CharacterDef(
        id: "kid:看", glyph: "看", level: 0,
        title: "看", subtitle: "眼睛看一看",
        strokes: [
            StrokeSpec(id: "k3_kan_1", name: "撇",
                       points: [.init(x: 0.66, y: 0.16),
                                .init(x: 0.30, y: 0.44)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["手字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_kan_2", name: "横",
                       points: [.init(x: 0.26, y: 0.28), .init(x: 0.78, y: 0.28)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["手字一横"], direction: "→"),
            StrokeSpec(id: "k3_kan_3", name: "横",
                       points: [.init(x: 0.22, y: 0.44), .init(x: 0.82, y: 0.44)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["手字长横"], direction: "→"),
            StrokeSpec(id: "k3_kan_4", name: "竖",
                       points: [.init(x: 0.38, y: 0.50), .init(x: 0.38, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["目字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_kan_5", name: "横折",
                       points: [.init(x: 0.38, y: 0.50),
                                .init(x: 0.76, y: 0.50),
                                .init(x: 0.76, y: 0.84)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["目字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_kan_6", name: "横",
                       points: [.init(x: 0.38, y: 0.62), .init(x: 0.76, y: 0.62)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["目字中横"], direction: "→"),
            StrokeSpec(id: "k3_kan_7", name: "横",
                       points: [.init(x: 0.38, y: 0.72), .init(x: 0.76, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["目字中横"], direction: "→"),
            StrokeSpec(id: "k3_kan_8", name: "横",
                       points: [.init(x: 0.38, y: 0.84), .init(x: 0.76, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.07,
                       tips: ["目字底横"], direction: "→")
        ]
    )

    // 听 (7 画): 口 + 斤
    static let 听 = CharacterDef(
        id: "kid:听", glyph: "听", level: 0,
        title: "听", subtitle: "用耳朵听一听",
        strokes: [
            StrokeSpec(id: "k3_ting_1", name: "竖",
                       points: [.init(x: 0.16, y: 0.42), .init(x: 0.16, y: 0.72)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["口字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_ting_2", name: "横折",
                       points: [.init(x: 0.16, y: 0.42),
                                .init(x: 0.40, y: 0.42),
                                .init(x: 0.40, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_ting_3", name: "横",
                       points: [.init(x: 0.16, y: 0.72), .init(x: 0.40, y: 0.72)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字底横"], direction: "→"),
            StrokeSpec(id: "k3_ting_4", name: "撇",
                       points: [.init(x: 0.66, y: 0.22),
                                .init(x: 0.52, y: 0.44)],
                       widthStart: 0.08, widthEnd: 0.03,
                       tips: ["斤字撇"], direction: "↙"),
            StrokeSpec(id: "k3_ting_5", name: "撇",
                       points: [.init(x: 0.62, y: 0.40),
                                .init(x: 0.52, y: 0.60),
                                .init(x: 0.48, y: 0.82)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["斤字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_ting_6", name: "横",
                       points: [.init(x: 0.50, y: 0.52), .init(x: 0.88, y: 0.52)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["斤字一横"], direction: "→"),
            StrokeSpec(id: "k3_ting_7", name: "竖",
                       points: [.init(x: 0.80, y: 0.52), .init(x: 0.80, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["斤字一竖"], direction: "↓")
        ]
    )

    // 走 (7 画): 土 + 疋
    static let 走 = CharacterDef(
        id: "kid:走", glyph: "走", level: 0,
        title: "走", subtitle: "慢慢走一走",
        strokes: [
            StrokeSpec(id: "k3_zou_1", name: "横",
                       points: [.init(x: 0.30, y: 0.22), .init(x: 0.72, y: 0.22)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["土字上横"], direction: "→"),
            StrokeSpec(id: "k3_zou_2", name: "竖",
                       points: [.init(x: 0.50, y: 0.22), .init(x: 0.50, y: 0.52)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中间一竖"], direction: "↓"),
            StrokeSpec(id: "k3_zou_3", name: "横",
                       points: [.init(x: 0.20, y: 0.40), .init(x: 0.80, y: 0.40)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["中间长横"], direction: "→"),
            StrokeSpec(id: "k3_zou_4", name: "竖",
                       points: [.init(x: 0.42, y: 0.52), .init(x: 0.42, y: 0.74)],
                       widthStart: 0.06, widthEnd: 0.05,
                       tips: ["下半竖"], direction: "↓"),
            StrokeSpec(id: "k3_zou_5", name: "横",
                       points: [.init(x: 0.28, y: 0.64), .init(x: 0.60, y: 0.64)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["下半横"], direction: "→"),
            StrokeSpec(id: "k3_zou_6", name: "撇",
                       points: [.init(x: 0.42, y: 0.64),
                                .init(x: 0.22, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["左撇"], direction: "↙"),
            StrokeSpec(id: "k3_zou_7", name: "捺",
                       points: [.init(x: 0.42, y: 0.64),
                                .init(x: 0.68, y: 0.78),
                                .init(x: 0.88, y: 0.86)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["右下长捺"], direction: "↘")
        ]
    )

    // 跑 (简化 12→8 画): 足 + 包骨架
    static let 跑 = CharacterDef(
        id: "kid:跑", glyph: "跑", level: 0,
        title: "跑", subtitle: "快快跑起来",
        strokes: [
            StrokeSpec(id: "k3_pao_1", name: "竖",
                       points: [.init(x: 0.20, y: 0.22), .init(x: 0.20, y: 0.40)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["口字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_pao_2", name: "横折",
                       points: [.init(x: 0.20, y: 0.22),
                                .init(x: 0.40, y: 0.22),
                                .init(x: 0.40, y: 0.40)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_pao_3", name: "横",
                       points: [.init(x: 0.20, y: 0.40), .init(x: 0.40, y: 0.40)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字底横"], direction: "→"),
            StrokeSpec(id: "k3_pao_4", name: "竖",
                       points: [.init(x: 0.30, y: 0.46), .init(x: 0.30, y: 0.74)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["足字竖"], direction: "↓"),
            StrokeSpec(id: "k3_pao_5", name: "提",
                       points: [.init(x: 0.14, y: 0.86), .init(x: 0.44, y: 0.76)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["足字一提"], direction: "↗"),
            StrokeSpec(id: "k3_pao_6", name: "撇",
                       points: [.init(x: 0.74, y: 0.18),
                                .init(x: 0.54, y: 0.44),
                                .init(x: 0.50, y: 0.72)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["包字外撇"], direction: "↙"),
            StrokeSpec(id: "k3_pao_7", name: "横折钩",
                       points: [.init(x: 0.66, y: 0.28),
                                .init(x: 0.88, y: 0.28),
                                .init(x: 0.88, y: 0.74),
                                .init(x: 0.78, y: 0.68)],
                       widthStart: 0.06, widthEnd: 0.03,
                       tips: ["包字横折钩"], direction: "→↓↖"),
            StrokeSpec(id: "k3_pao_8", name: "横",
                       points: [.init(x: 0.64, y: 0.50), .init(x: 0.84, y: 0.50)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["巳字一横"], direction: "→")
        ]
    )

    // 坐 (7 画): 人人 + 土
    static let 坐 = CharacterDef(
        id: "kid:坐", glyph: "坐", level: 0,
        title: "坐", subtitle: "好好坐下来",
        strokes: [
            StrokeSpec(id: "k3_zuo_1", name: "撇",
                       points: [.init(x: 0.32, y: 0.20),
                                .init(x: 0.22, y: 0.38)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["左人撇"], direction: "↙"),
            StrokeSpec(id: "k3_zuo_2", name: "捺",
                       points: [.init(x: 0.32, y: 0.20),
                                .init(x: 0.42, y: 0.38)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["左人捺"], direction: "↘"),
            StrokeSpec(id: "k3_zuo_3", name: "撇",
                       points: [.init(x: 0.68, y: 0.20),
                                .init(x: 0.58, y: 0.38)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["右人撇"], direction: "↙"),
            StrokeSpec(id: "k3_zuo_4", name: "捺",
                       points: [.init(x: 0.68, y: 0.20),
                                .init(x: 0.78, y: 0.38)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["右人捺"], direction: "↘"),
            StrokeSpec(id: "k3_zuo_5", name: "竖",
                       points: [.init(x: 0.50, y: 0.38), .init(x: 0.50, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中间一竖"], direction: "↓"),
            StrokeSpec(id: "k3_zuo_6", name: "横",
                       points: [.init(x: 0.34, y: 0.62), .init(x: 0.66, y: 0.62)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["土字中横"], direction: "→"),
            StrokeSpec(id: "k3_zuo_7", name: "横",
                       points: [.init(x: 0.14, y: 0.84), .init(x: 0.86, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["土字底横"], direction: "→")
        ]
    )

    // 站 (简化 10→7 画): 立 + 占
    static let 站 = CharacterDef(
        id: "kid:站", glyph: "站", level: 0,
        title: "站", subtitle: "站直身体",
        strokes: [
            StrokeSpec(id: "k3_zhan_1", name: "点",
                       points: [.init(x: 0.20, y: 0.18), .init(x: 0.24, y: 0.28)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["立字顶点"], direction: "●"),
            StrokeSpec(id: "k3_zhan_2", name: "横",
                       points: [.init(x: 0.08, y: 0.32), .init(x: 0.40, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["立字一横"], direction: "→"),
            StrokeSpec(id: "k3_zhan_3", name: "点",
                       points: [.init(x: 0.12, y: 0.44), .init(x: 0.08, y: 0.54)],
                       widthStart: 0.03, widthEnd: 0.07,
                       tips: ["立字左点"], direction: "●"),
            StrokeSpec(id: "k3_zhan_4", name: "撇",
                       points: [.init(x: 0.32, y: 0.44),
                                .init(x: 0.38, y: 0.54)],
                       widthStart: 0.06, widthEnd: 0.02,
                       tips: ["立字右撇"], direction: "↙"),
            StrokeSpec(id: "k3_zhan_5", name: "提",
                       points: [.init(x: 0.08, y: 0.68), .init(x: 0.42, y: 0.62)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["立字底提"], direction: "↗"),
            StrokeSpec(id: "k3_zhan_6", name: "竖",
                       points: [.init(x: 0.64, y: 0.22), .init(x: 0.64, y: 0.42)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["占字上竖"], direction: "↓"),
            StrokeSpec(id: "k3_zhan_7", name: "横",
                       points: [.init(x: 0.50, y: 0.42), .init(x: 0.88, y: 0.42)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["占字一横"], direction: "→"),
            StrokeSpec(id: "k3_zhan_8", name: "竖",
                       points: [.init(x: 0.58, y: 0.52), .init(x: 0.58, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["口字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_zhan_9", name: "横折",
                       points: [.init(x: 0.58, y: 0.52),
                                .init(x: 0.86, y: 0.52),
                                .init(x: 0.86, y: 0.84)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["口字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_zhan_10", name: "横",
                       points: [.init(x: 0.58, y: 0.84), .init(x: 0.86, y: 0.84)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["口字底横"], direction: "→")
        ]
    )

    // ─── 家人 6 字 ─────────────────────────────────

    // 爸 (8 画): 父 + 巴
    static let 爸 = CharacterDef(
        id: "kid:爸", glyph: "爸", level: 0,
        title: "爸", subtitle: "我的爸爸",
        strokes: [
            StrokeSpec(id: "k3_ba_1", name: "点",
                       points: [.init(x: 0.30, y: 0.16), .init(x: 0.26, y: 0.26)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["父字左点"], direction: "●"),
            StrokeSpec(id: "k3_ba_2", name: "撇",
                       points: [.init(x: 0.70, y: 0.16),
                                .init(x: 0.74, y: 0.26)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["父字右撇"], direction: "↙"),
            StrokeSpec(id: "k3_ba_3", name: "撇",
                       points: [.init(x: 0.60, y: 0.26),
                                .init(x: 0.20, y: 0.56)],
                       widthStart: 0.08, widthEnd: 0.02,
                       tips: ["父字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_ba_4", name: "捺",
                       points: [.init(x: 0.40, y: 0.26),
                                .init(x: 0.80, y: 0.56)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["父字长捺"], direction: "↘"),
            StrokeSpec(id: "k3_ba_5", name: "横",
                       points: [.init(x: 0.28, y: 0.60), .init(x: 0.62, y: 0.60)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["巴字一横"], direction: "→"),
            StrokeSpec(id: "k3_ba_6", name: "竖",
                       points: [.init(x: 0.28, y: 0.60), .init(x: 0.28, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["巴字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_ba_7", name: "横",
                       points: [.init(x: 0.28, y: 0.74), .init(x: 0.62, y: 0.74)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["巴字中横"], direction: "→"),
            StrokeSpec(id: "k3_ba_8", name: "竖弯钩",
                       points: [.init(x: 0.62, y: 0.60),
                                .init(x: 0.62, y: 0.84),
                                .init(x: 0.84, y: 0.84),
                                .init(x: 0.84, y: 0.74)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["巴字竖弯钩"], direction: "↓→↑")
        ]
    )

    // 妈 (6 画): 女 + 马
    static let 妈 = CharacterDef(
        id: "kid:妈", glyph: "妈", level: 0,
        title: "妈", subtitle: "我的妈妈",
        strokes: [
            StrokeSpec(id: "k3_ma_1", name: "撇点",
                       points: [.init(x: 0.32, y: 0.24),
                                .init(x: 0.14, y: 0.46),
                                .init(x: 0.30, y: 0.58)],
                       widthStart: 0.07, widthEnd: 0.05,
                       tips: ["女字撇点"], direction: "↙↘"),
            StrokeSpec(id: "k3_ma_2", name: "撇",
                       points: [.init(x: 0.36, y: 0.34),
                                .init(x: 0.20, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["女字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_ma_3", name: "提",
                       points: [.init(x: 0.14, y: 0.70), .init(x: 0.40, y: 0.64)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["女字一提"], direction: "↗"),
            StrokeSpec(id: "k3_ma_4", name: "横折",
                       points: [.init(x: 0.50, y: 0.28),
                                .init(x: 0.82, y: 0.28),
                                .init(x: 0.82, y: 0.48)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["马字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_ma_5", name: "横",
                       points: [.init(x: 0.50, y: 0.48), .init(x: 0.82, y: 0.48)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["马字横"], direction: "→"),
            StrokeSpec(id: "k3_ma_6", name: "竖弯钩",
                       points: [.init(x: 0.50, y: 0.32),
                                .init(x: 0.50, y: 0.76),
                                .init(x: 0.88, y: 0.76),
                                .init(x: 0.88, y: 0.62)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["马字竖弯钩"], direction: "↓→↑"),
            StrokeSpec(id: "k3_ma_7", name: "横",
                       points: [.init(x: 0.46, y: 0.76), .init(x: 0.88, y: 0.76)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["马字底横"], direction: "→")
        ]
    )

    // 哥 (简化 10→7 画): 可 x 2 骨架
    static let 哥 = CharacterDef(
        id: "kid:哥", glyph: "哥", level: 0,
        title: "哥", subtitle: "我的哥哥",
        strokes: [
            StrokeSpec(id: "k3_ge_1", name: "横",
                       points: [.init(x: 0.20, y: 0.18), .init(x: 0.80, y: 0.18)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["上面一横"], direction: "→"),
            StrokeSpec(id: "k3_ge_2", name: "竖",
                       points: [.init(x: 0.34, y: 0.26), .init(x: 0.34, y: 0.46)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["上口左竖"], direction: "↓"),
            StrokeSpec(id: "k3_ge_3", name: "横折",
                       points: [.init(x: 0.34, y: 0.26),
                                .init(x: 0.66, y: 0.26),
                                .init(x: 0.66, y: 0.46)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["上口横折"], direction: "→↓"),
            StrokeSpec(id: "k3_ge_4", name: "横",
                       points: [.init(x: 0.14, y: 0.52), .init(x: 0.86, y: 0.52)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["中间长横"], direction: "→"),
            StrokeSpec(id: "k3_ge_5", name: "竖",
                       points: [.init(x: 0.30, y: 0.60), .init(x: 0.30, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["下口左竖"], direction: "↓"),
            StrokeSpec(id: "k3_ge_6", name: "横折",
                       points: [.init(x: 0.30, y: 0.60),
                                .init(x: 0.60, y: 0.60),
                                .init(x: 0.60, y: 0.82)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["下口横折"], direction: "→↓"),
            StrokeSpec(id: "k3_ge_7", name: "横",
                       points: [.init(x: 0.30, y: 0.82), .init(x: 0.60, y: 0.82)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["下口底横"], direction: "→"),
            StrokeSpec(id: "k3_ge_8", name: "竖钩",
                       points: [.init(x: 0.80, y: 0.52),
                                .init(x: 0.80, y: 0.84),
                                .init(x: 0.72, y: 0.80)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["右边竖钩"], direction: "↓↖")
        ]
    )

    // 姐 (8 画): 女 + 且
    static let 姐 = CharacterDef(
        id: "kid:姐", glyph: "姐", level: 0,
        title: "姐", subtitle: "我的姐姐",
        strokes: [
            StrokeSpec(id: "k3_jie_1", name: "撇点",
                       points: [.init(x: 0.32, y: 0.24),
                                .init(x: 0.14, y: 0.46),
                                .init(x: 0.30, y: 0.58)],
                       widthStart: 0.07, widthEnd: 0.05,
                       tips: ["女字撇点"], direction: "↙↘"),
            StrokeSpec(id: "k3_jie_2", name: "撇",
                       points: [.init(x: 0.36, y: 0.34),
                                .init(x: 0.20, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["女字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_jie_3", name: "提",
                       points: [.init(x: 0.14, y: 0.70), .init(x: 0.40, y: 0.64)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["女字一提"], direction: "↗"),
            StrokeSpec(id: "k3_jie_4", name: "竖",
                       points: [.init(x: 0.54, y: 0.22), .init(x: 0.54, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["且字左竖"], direction: "↓"),
            StrokeSpec(id: "k3_jie_5", name: "横折",
                       points: [.init(x: 0.54, y: 0.22),
                                .init(x: 0.86, y: 0.22),
                                .init(x: 0.86, y: 0.82)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["且字横折"], direction: "→↓"),
            StrokeSpec(id: "k3_jie_6", name: "横",
                       points: [.init(x: 0.54, y: 0.42), .init(x: 0.86, y: 0.42)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["且字中横"], direction: "→"),
            StrokeSpec(id: "k3_jie_7", name: "横",
                       points: [.init(x: 0.54, y: 0.62), .init(x: 0.86, y: 0.62)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["且字中横"], direction: "→"),
            StrokeSpec(id: "k3_jie_8", name: "横",
                       points: [.init(x: 0.48, y: 0.82), .init(x: 0.88, y: 0.82)],
                       widthStart: 0.07, widthEnd: 0.07,
                       tips: ["且字底横"], direction: "→")
        ]
    )

    // 弟 (7 画): 点 + 撇 + 丨 + 丷 + 弓
    static let 弟 = CharacterDef(
        id: "kid:弟", glyph: "弟", level: 0,
        title: "弟", subtitle: "我的弟弟",
        strokes: [
            StrokeSpec(id: "k3_di_1", name: "点",
                       points: [.init(x: 0.36, y: 0.14), .init(x: 0.34, y: 0.24)],
                       widthStart: 0.03, widthEnd: 0.08,
                       tips: ["左上一点"], direction: "●"),
            StrokeSpec(id: "k3_di_2", name: "撇",
                       points: [.init(x: 0.64, y: 0.14),
                                .init(x: 0.66, y: 0.24)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["右上一撇"], direction: "↙"),
            StrokeSpec(id: "k3_di_3", name: "横",
                       points: [.init(x: 0.22, y: 0.32), .init(x: 0.78, y: 0.32)],
                       widthStart: 0.06, widthEnd: 0.07,
                       tips: ["上面一横"], direction: "→"),
            StrokeSpec(id: "k3_di_4", name: "竖折",
                       points: [.init(x: 0.34, y: 0.32),
                                .init(x: 0.34, y: 0.54),
                                .init(x: 0.66, y: 0.54)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["中间竖折"], direction: "↓→"),
            StrokeSpec(id: "k3_di_5", name: "横",
                       points: [.init(x: 0.22, y: 0.54), .init(x: 0.66, y: 0.54)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["一横"], direction: "→"),
            StrokeSpec(id: "k3_di_6", name: "竖折折钩",
                       points: [.init(x: 0.66, y: 0.32),
                                .init(x: 0.66, y: 0.68),
                                .init(x: 0.30, y: 0.68),
                                .init(x: 0.30, y: 0.82),
                                .init(x: 0.22, y: 0.78)],
                       widthStart: 0.07, widthEnd: 0.03,
                       tips: ["竖折折钩"], direction: "↓←↓↖"),
            StrokeSpec(id: "k3_di_7", name: "竖",
                       points: [.init(x: 0.50, y: 0.34), .init(x: 0.50, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["中间长竖"], direction: "↓")
        ]
    )

    // 妹 (8 画): 女 + 未
    static let 妹 = CharacterDef(
        id: "kid:妹", glyph: "妹", level: 0,
        title: "妹", subtitle: "我的妹妹",
        strokes: [
            StrokeSpec(id: "k3_mei_1", name: "撇点",
                       points: [.init(x: 0.32, y: 0.24),
                                .init(x: 0.14, y: 0.46),
                                .init(x: 0.30, y: 0.58)],
                       widthStart: 0.07, widthEnd: 0.05,
                       tips: ["女字撇点"], direction: "↙↘"),
            StrokeSpec(id: "k3_mei_2", name: "撇",
                       points: [.init(x: 0.36, y: 0.34),
                                .init(x: 0.20, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["女字长撇"], direction: "↙"),
            StrokeSpec(id: "k3_mei_3", name: "提",
                       points: [.init(x: 0.14, y: 0.70), .init(x: 0.40, y: 0.64)],
                       widthStart: 0.09, widthEnd: 0.02,
                       tips: ["女字一提"], direction: "↗"),
            StrokeSpec(id: "k3_mei_4", name: "横",
                       points: [.init(x: 0.52, y: 0.30), .init(x: 0.82, y: 0.30)],
                       widthStart: 0.06, widthEnd: 0.06,
                       tips: ["未字短横"], direction: "→"),
            StrokeSpec(id: "k3_mei_5", name: "横",
                       points: [.init(x: 0.46, y: 0.48), .init(x: 0.88, y: 0.48)],
                       widthStart: 0.07, widthEnd: 0.08,
                       tips: ["未字长横"], direction: "→"),
            StrokeSpec(id: "k3_mei_6", name: "竖",
                       points: [.init(x: 0.66, y: 0.22), .init(x: 0.66, y: 0.86)],
                       widthStart: 0.07, widthEnd: 0.06,
                       tips: ["未字竖"], direction: "↓"),
            StrokeSpec(id: "k3_mei_7", name: "撇",
                       points: [.init(x: 0.60, y: 0.58),
                                .init(x: 0.46, y: 0.84)],
                       widthStart: 0.07, widthEnd: 0.02,
                       tips: ["未字撇"], direction: "↙"),
            StrokeSpec(id: "k3_mei_8", name: "捺",
                       points: [.init(x: 0.72, y: 0.58),
                                .init(x: 0.88, y: 0.84)],
                       widthStart: 0.03, widthEnd: 0.11,
                       tips: ["未字捺"], direction: "↘")
        ]
    )

    // ─── 分组 ──────────────────────────────────────

    static let groups: [(title: String, chars: [CharacterDef])] = [
        ("颜色 · 红黄蓝绿白黑", [红, 黄, 蓝, 绿, 白, 黑]),
        ("食物 · 米奶饭菜果吃", [米, 奶, 饭, 菜, 果, 吃]),
        ("家居 · 家门窗床桌椅", [家, 门, 窗, 床, 桌, 椅]),
        ("动作 · 看听走跑坐站", [看, 听, 走, 跑, 坐, 站]),
        ("家人 · 爸妈哥姐弟妹", [爸, 妈, 哥, 姐, 弟, 妹])
    ]

    /// 扁平全部 30 字，按学习顺序
    static var all: [CharacterDef] {
        groups.flatMap { $0.chars }
    }

    // ─── 元数据：pinyin / emoji / meaning / sticker / cheer ─────

    static let meta: [String: KidsCharacters.Meta] = [
        // 颜色
        "kid:红": .init(pinyin: "hóng",  emoji: "🔴",  meaning: "红色",   sticker: "❤️",  cheer: nil),
        "kid:黄": .init(pinyin: "huáng", emoji: "🟡",  meaning: "黄色",   sticker: "🌻",  cheer: nil),
        "kid:蓝": .init(pinyin: "lán",   emoji: "🔵",  meaning: "蓝色",   sticker: "🌀",  cheer: nil),
        "kid:绿": .init(pinyin: "lǜ",    emoji: "🟢",  meaning: "绿色",   sticker: "🍀",  cheer: nil),
        "kid:白": .init(pinyin: "bái",   emoji: "⚪",  meaning: "白色",   sticker: "☁️",  cheer: nil),
        "kid:黑": .init(pinyin: "hēi",   emoji: "⚫",  meaning: "黑色",   sticker: "🌚",  cheer: nil),

        // 食物
        "kid:米": .init(pinyin: "mǐ",    emoji: "🍚",  meaning: "大米",   sticker: "🌾",  cheer: nil),
        "kid:奶": .init(pinyin: "nǎi",   emoji: "🥛",  meaning: "牛奶",   sticker: "🥛",  cheer: nil),
        "kid:饭": .init(pinyin: "fàn",   emoji: "🍚",  meaning: "米饭",   sticker: "🍱",  cheer: nil),
        "kid:菜": .init(pinyin: "cài",   emoji: "🥬",  meaning: "蔬菜",   sticker: "🥗",  cheer: nil),
        "kid:果": .init(pinyin: "guǒ",   emoji: "🍎",  meaning: "水果",   sticker: "🍎",  cheer: "好吃!"),
        "kid:吃": .init(pinyin: "chī",   emoji: "😋",  meaning: "吃饭",   sticker: "🍽️", cheer: nil),

        // 家居
        "kid:家": .init(pinyin: "jiā",   emoji: "🏠",  meaning: "家",     sticker: "🏡",  cheer: "回家啦~"),
        "kid:门": .init(pinyin: "mén",   emoji: "🚪",  meaning: "门",     sticker: "🚪",  cheer: nil),
        "kid:窗": .init(pinyin: "chuāng",emoji: "🪟",  meaning: "窗户",   sticker: "🪟",  cheer: nil),
        "kid:床": .init(pinyin: "chuáng",emoji: "🛏️", meaning: "床",     sticker: "🛌",  cheer: nil),
        "kid:桌": .init(pinyin: "zhuō",  emoji: "🪑",  meaning: "桌子",   sticker: "🪑",  cheer: nil),
        "kid:椅": .init(pinyin: "yǐ",    emoji: "💺",  meaning: "椅子",   sticker: "💺",  cheer: nil),

        // 动作
        "kid:看": .init(pinyin: "kàn",   emoji: "👀",  meaning: "看见",   sticker: "👓",  cheer: nil),
        "kid:听": .init(pinyin: "tīng",  emoji: "👂",  meaning: "听见",   sticker: "🎧",  cheer: nil),
        "kid:走": .init(pinyin: "zǒu",   emoji: "🚶",  meaning: "走路",   sticker: "👣",  cheer: nil),
        "kid:跑": .init(pinyin: "pǎo",   emoji: "🏃",  meaning: "跑步",   sticker: "🏃",  cheer: "跑起来!"),
        "kid:坐": .init(pinyin: "zuò",   emoji: "🧘",  meaning: "坐下",   sticker: "💺",  cheer: nil),
        "kid:站": .init(pinyin: "zhàn",  emoji: "🧍",  meaning: "站立",   sticker: "🕴️", cheer: nil),

        // 家人
        "kid:爸": .init(pinyin: "bà",    emoji: "👨",  meaning: "爸爸",   sticker: "👨‍👧", cheer: "爸爸来抱~"),
        "kid:妈": .init(pinyin: "mā",    emoji: "👩",  meaning: "妈妈",   sticker: "👩‍👧", cheer: "妈妈最好"),
        "kid:哥": .init(pinyin: "gē",    emoji: "👦",  meaning: "哥哥",   sticker: "👦",  cheer: nil),
        "kid:姐": .init(pinyin: "jiě",   emoji: "👧",  meaning: "姐姐",   sticker: "👧",  cheer: nil),
        "kid:弟": .init(pinyin: "dì",    emoji: "🧒",  meaning: "弟弟",   sticker: "🧒",  cheer: nil),
        "kid:妹": .init(pinyin: "mèi",   emoji: "👶",  meaning: "妹妹",   sticker: "👶",  cheer: nil)
    ]

    static func metaFor(_ id: String) -> KidsCharacters.Meta? { meta[id] }
}
